baseURL = "https://chrisalexander.me.uk/"
theme = "hugo-bearcub"
copyright = "Copyright Â© 2024, Chris Alexander"
defaultContentLanguage = "en"
hasCJKLanguage = true

enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true

[markup]
  [markup.highlight]
  lineNos = true
  lineNumbersInTable = false
  noClasses = false

[languages]
  [languages.en]
    title = "Chris Alexander"
    languageName = "English ğŸ‡¬ğŸ‡§"
    languageCode = "en-GB"
    contentDir = "content"
    weight = 1
  [languages.en.params]
    madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"
  [languages.jp]
    title = "Chris Alexander"
    languageName = "æ—¥æœ¬èª ğŸ‡¯ğŸ‡µ"
    languageCode = "ja-JP"
    contentDir = "content.jp"
    weight = 2
  [languages.jp.params]
    madeWith = "[Bear Cub](https://github.com/clente/hugo-bearcub)ã§ä½œæˆ"

[params]
  description = "Chris Alexander's personal website"
  title = "Chris Alexander"

  favicon = "/favicon.ico"
  themeStyle = "original"

  [params.author]
    name = "Chris Alexander"
